// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'player_move_request.mapper.dart';

@MappableClass(
  caseStyle: CaseStyle.snakeCase,
)
class PlayerMoveRequest with PlayerMoveRequestMappable {
  final int positionX;
  final int positionY;
  PlayerMoveRequest(this.positionX, this.positionY);
}
